###
# PAIRS IN PAPER
# NOTE: to successfully OM each pair, run `make imports-parseable` 
# since some source-target pairs have imports that hang or require RDF conversion
# _the easiest way to re-produce our mappings is to run `make` in a fresh repo w/ deps installed_
###

pairs:
  - source: uco1-merge
    target: stix-spec-merged
  - source: stix-spec-merged
    target: d3fend-rdf-xml
  - source: JC3IEDM
    target: mIOmerged-noimports
  - source: JC3IEDM
    target: Brick+imports
  - source: ThinkHomeMerged
    target: Brick+imports
  - source: Brick+imports
    target: SmartEnvMerged
  - source: CityOWLmerged
    target: Brick+imports
  - source: JC3IEDM
    target: FacilityOntology-noimports